(defun color-theme-emacsmonokai ()
  "A color theme based on Sublime Text."
  (interactive)
  (color-theme-install
   '(color-theme-emacsmonokai
     (
      (background-color . "#272822")
      (foreground-color . "#F8F8F2")
      (background-mode . light)
      (border-color . "#C7EDCC")
      (cursor-color . "#8EFA00")
      )
     ((help-highlight-face . underline)
      )
     (hl-line ((t (:background "#383830"))))
     (linum ((t (:foreground "gray58" :background "#272822" :bold nil :weight normal ))))
     (trailing-whitespace ((((class color) (background light)) (:background "#F92672":bold t))))
     (whitespace-line ((t (:background "lemon chiffon" :foreground "dark violet":bold t))))
     (geben-cursor-arrow-face ((t (:background "#F92672" :bold t))))
     (fringe ((t (:background "#272822"))))
     (mode-line ((t (:foreground "#F8F8F2":bold t :height 1.0 :background "#49483E" :box (:style released-button)))))
     (region ((t (:background "#49483E"))))
     (font-latex-math-face ((t (:foreground "#8f5902"))))
     (font-latex-sedate-face ((t (:foreground "#AE81FF"))))
     (font-latex-warning-face ((t (:foreground "#F92672" :bold nil))))
     (font-lock-builtin-face ((t (:foreground "#3465a4"))))
     (ioccur-match-face ((t (:background "yellow"))))
     (ioccur-regexp-face ((t (:background "yellow"))))
     (font-lock-comment-face ((t (:foreground "#75715E"))))
     (font-lock-constant-face ((t (:foreground "#A6E22E" ))))
     (font-lock-doc-face ((t (:foreground "#E6DB74"))))
     (font-lock-keyword-face ((t (:foreground "#66D9EF" ))))
     (font-lock-type-face ((t (:foreground "#AE81FF"))))
     (font-lock-variable-name-face ((t (:foreground "#B92A2A"))))
     (font-lock-warning-face ((t (:foreground "#F92672"))))
     (font-lock-function-name-face ((t (:foreground "#A6E22E"))))
     (comint-highlight-input ((t (:italic t :bold nil))))
     (comint-highlight-prompt ((t (:foreground "#8ae234"))))
     (font-lock-string-face ((t (:foreground "#E6DB74"))))
     (show-paren-match-face ((t (:foreground "#000000" :background "#FD971F"))))
     (show-paren-mismatch-face ((t (:foreground "#960050" :background "#1E0010"))))
     (minimap-active-region-background ((t (:foreground nil :background "#383830"))))
     (rainbow-delimiters-depth-1-face ((((background light)) (:foreground "#A6E22E":bold t))))
     (rainbow-delimiters-depth-2-face ((((background light)) (:foreground "#AE81FF":bold t))))
     (rainbow-delimiters-depth-3-face ((((background light)) (:foreground "#F92672":bold t))))
     (rainbow-delimiters-depth-4-face ((((background light)) (:foreground "#E6DB74":bold t))))
     (rainbow-delimiters-depth-5-face ((((background light)) (:foreground "#AE81FF":bold t))))
     (rainbow-delimiters-depth-6-face ((((background light)) (:foreground "#66D9EF":bold t))))
     (rainbow-delimiters-depth-7-face ((((background light)) (:foreground "#FD971F":bold t))))
     (rainbow-delimiters-depth-8-face ((((background light)) (:foreground "#F8F8F0":bold t))))
     (rainbow-delimiters-depth-9-face ((((background light)) (:foreground "#33aaff":bold t))))
     (woman-addition ((t (:foreground "#AE81FF"))))
     (woman-bold ((t (:foreground "#F92672"))))
     (woman-italic ((t (:foreground "#A6E22E"))))
     (woman-unknown ((t (:foreground "#66D9EF"))))
     (diff-added ((t (:foreground "#A6E22E" :weight bold))))
     (diff-context ((t (:foreground "#F8F8F2"))))
     (diff-file-header ((t (:foreground "#66D9EF" :background nil))))
     (diff-indicator-added ((t (:foreground "#A6E22E"))))
     (diff-indicator-removed ((t (:foreground "#F92672"))))
     (diff-header ((t (:foreground "#F8F8F2" :background "#232526"))))
     (diff-hunk-header ((t (:foreground "#AE81FF" :background "#232526"))))
     (diff-removed ((t (:foreground "#F92672" :weight bold))))
     (markdown-italic-face ((t (:slant italic))))
     (markdown-bold-face ((t (:weight bold))))
     (markdown-header-face ((t (:weight normal))))
     (markdown-header-face-1 ((t (:foreground "#66D9EF"))))
     (markdown-header-face-2 ((t (:foreground "#F92672"))))
     (markdown-header-face-3 ((t (:foreground "#A6E22E"))))
     (markdown-header-face-4 ((t (:foreground "#AE81FF"))))
     (markdown-header-face-5 ((t (:foreground "#E6DB74"))))
     (markdown-header-face-6 ((t (:foreground "#66D9EF"))))
     (markdown-inline-code-face ((t (:foreground "#66D9EF"))))
     (markdown-list-face ((t (:foreground "#A6E22E"))))
     (markdown-blockquote-face ((t (:slant italic))))
     (markdown-pre-face ((t (:foreground "#AE81FF"))))
     (markdown-link-face ((t (:foreground "#66D9EF"))))
     (markdown-reference-face ((t (:foreground "#66D9EF"))))
     (markdown-url-face ((t (:foreground "#E6DB74"))))
     (markdown-link-title-face ((t (:foreground "#F92672"))))
     (markdown-comment-face ((t (:foreground "#465457"))))
     (markdown-math-face ((t (:foreground "#AE81FF" :slant italic))))
     (icompletep-choices ((t (:foreground "#F92672"))))
     (icompletep-determined ((t (:foreground "#A6E22E"))))
     (icompletep-keys ((t (:foreground "#F92672"))))
     (icompletep-nb-candidates ((t (:foreground "#AE81FF"))))
     (org-todo ((t (:foreground "#0033cc" :bold t))))
     (org-done ((t (:bold t :foreground "ForestGreen"))))
     (Org-warning ((t (:foreground "#0033cc" :bold t))))
     (outline-1 ((t (:foreground "#66D9EF"))))
     (outline-2 ((t (:foreground "#F92672"))))
     (outline-3 ((t (:foreground "#A6E22E"))))
     (outline-4 ((t (:foreground "#AE81FF"))))
     (outline-5 ((t (:foreground "#E6DB74"))))
     (outline-6 ((t (:foreground "#66D9EF"))))
     (outline-7 ((t (:foreground "#F92672"))))
     (outline-8 ((t (:foreground "#A6E22E"))))
     (org-agenda-structure ((t (:weight bold :foreground "tomato"))))
     (org-agenda-date ((t (:foreground "#6ac214"))))
     (org-agenda-date-weekend ((t (:weight normal :foreground "dodger blue"))))
     (org-agenda-date-today ((t (:weight bold :foreground "#edd400"))))
     (minibuffer-prompt ((t (:foreground "#66D9EF"))))
     (info-xref ((t (:foreground "#3465a4"))))
     (info-xref-visited ((t (:foreground "#75507b"))))
     (highlight ((t (:background "#383830"))))
     )))
(provide 'color-theme-emacsmonokai)
